AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy resources for bedrock project

Parameters:
  LambdaCodeBucket:
    Type: String

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LambdaCodeBucket
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !ImportValue Bedrock-LambdaBetaArn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: beta/prompt_inputs/
          - Event: "s3:ObjectCreated:*"
            Function: !ImportValue Bedrock-LambdaProdArn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: prod/prompt_inputs/

  # S3EventBucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: !Ref S3Bucket
  #     PolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Sid: TranscribeReadAll
  #           Effect: Allow
  #           Principal: { Service: transcribe.amazonaws.com }
  #           Action:
  #             - s3:GetObject
  #             - s3:GetObjectVersion
  #           Resource:
  #             - !Sub "arn:${AWS::Partition}:s3:::${S3Bucket}/*"
  #           Condition:
  #             StringEquals:
  #               aws:SourceAccount: !Ref AWS::AccountId